### PR TITLE
Attempts to try to set bare-strings to true in template-lintrc

### PR DESCRIPTION
**Pull request by jasonmit**
/cc @rwjblue

https://github.com/rwjblue/ember-template-lint/pull/27

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by rwjblue** [comment]
Looks good! I think I'd still like a flag on the addon so that I can warn in ember-cli-template-lint when the rule isn't set explicitly (either true or false) in the config file.

**Comment by rwjblue** [comment]
After thinking about it some more, maybe ember-cli-template-lint should do this in its blueprint instead of both ember-intl and ember-i18n both doing it?  In ember-cli-template-lint I would check for the flag discussed above (and in the ember-template-lint issue) and generate the default blueprint with `bare-strings` enabled.  Then each time we go to do a lint run, I could also check and confirm that `bare-strings` is present in the rules list...

**Comment by rwjblue** [comment]
What do you think?

**Comment by jasonmit** [comment]
Fully on board with the flag on the addon.  Will close this and wait for that to land.

**Pull request closed without merging**
